[versions]
kotlinx-serialization = "1.6.3"
kotlin = "1.9.23"

[libraries]
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
serialization-toml = "com.akuleshov7:ktoml-core:0.5.1"
coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0"
process = "com.github.pgreze:kotlin-process:1.4.1"
xmlbuilder = "org.redundent:kotlin-xml-builder:1.9.1"
kodein-di = "org.kodein.di:kodein-di:7.21.2"
http4k-core = "org.http4k:http4k-core:5.14.4.0"
clikt = "com.github.ajalt.clikt:clikt:4.3.0"
mordant = "com.github.ajalt.mordant:mordant:2.4.0"
graalvm-native-buildtools = { module = "org.graalvm.buildtools.native:org.graalvm.buildtools.native.gradle.plugin", version = "0.10.1" }
graalvm-svm = "org.graalvm.nativeimage:svm:24.0.0"
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "6.22.0" }
arrow-core = "io.arrow-kt:arrow-core:1.2.3"
junit-bom = "org.junit:junit-bom:5.10.2"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
assertk = "com.willowtreeapps.assertk:assertk:0.28.0"

[plugins]
kotlinx-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
versions = "com.github.ben-manes.versions:0.51.0"
